### ISSUE TITLE
Keep filter settings in blueprints

### ISSUE THREAD

**Issue by agmlego** [Sil3ntStorm/factorio-filter-combinator#1]
It looks like these combinators do not save their settings in blueprints, making them kind of difficult to use in a wide scale.

**Comment by Sil3ntStorm** [comment]
That is correct, I also noticed this myself a few weeks ago. Need to check if I have that fix ready for deployment or if there were still some issues with that.
As mentioned (and the reason for the delay in response) I'm currently busy elsewhere, so it will take some time unfortunately. I might be able to push a new version at some point if the fix is complete and working. Otherwise it will have to wait until I find some more time to work on it.
